### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by vytautokas** [eleventigers/rxbus#2]
Can you add a method:    

public static AndroidRxBus create(RxBus.Logger logger) {
        return create(new AndroidQueueCache(), logger);
    }

to net.jokubasdargis.rxbus.AndroidRxBus ?

**Comment by eleventigers** [comment]
Added to v1.2.0 release (just synced to Maven Central), ref: https://github.com/eleventigers/rxbus/commit/aae900205d47870d586e71211c8108bc8f201212. 
Thanks for the suggestion!
